server:
  port: 8080
spring:
  application:
    name: "UserInteractions"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_ENDPOINT:http://localhost:8000}
    accessKey: fake
    secretKey: fake
queue:
  name: ${QUEUE_NAME:event.stats.validated}
commons:
  jms:
    output-concurrency: 10
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 0
    reactive: true
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
